### ISSUE TITLE
Issues using urls as install_requires

### ISSUE THREAD

**Issue by kingbuzzman** [pypa/setuptools#1758]
When installing `python setup.py install` it ignores my path, and gets the "best match" from pypi -- which its the **incorrect** version.

```
setup(
    name='Faker',
    ...
    install_requires=[
        ...
         "validators@https://github.com/kingbuzzman/validators/archive/0.13.0.tar.gz#egg=validators-0.13.0",  # TODO: this will change  # noqa
    ],
    ...
)
```

How do i get it to stop, and use my link? `pip install -e .` or `pip install .` does it correctly.

See here for more info: https://stackoverflow.com/questions/56046146/setup-py-ignores-full-path-dependencies-instead-looks-for-best-match-in-pypi

**Comment by benoit-pierre** [comment]
Using pip is the recommended way, otherwise you'll be hitting the deprecated `easy_install` code path.

**Comment by benoit-pierre** [comment]
Also note that if you intend to publish your package on PyPI, using a direct URL requirement will not work (they are not allowed by pip for "security" reasons).

**Comment by kingbuzzman** [comment]
@benoit-pierre This is an issues since i cant tell a project i dont own to start running their tests a different way.

**Comment by kingbuzzman** [comment]
Issue has been solved.

**Comment by madkote** [comment]
@kingbuzzman Hi, seems that issue is still present.

EXample:
```
'en-core-web-sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz#egg=en-core-web-sm'
```

Error:
```
ERROR: Could not find a version that satisfies the requirement en-core-web-sm (from mypack==6.0.0) (from versions: none)
ERROR: No matching distribution found for en-core-web-sm (from mypack==6.0.0)
```

**Comment by kingbuzzman** [comment]
@madkote Did you read `hoefling`'s answer over on [overflow](https://stackoverflow.com/questions/56046146/setup-py-ignores-full-path-dependencies-instead-looks-for-best-match-in-pypi)?

**Comment by madkote** [comment]
@kingbuzzman yes, otherwise I would not be here. Thanks for reply!
I use also `install_requires` and there is the issue.

Have a look here: https://stackoverflow.com/questions/64482089/python-setup-py-dependency-as-url-to-tar-or-git

**Comment by kingbuzzman** [comment]
@madkote you **must** use `dependency_links` otherwise it will not work.
