### ISSUE TITLE
[BUG] packages of the form package.something renamed to package_something in 75.8.1

### ISSUE THREAD

**Issue by krpatter-intc** [pypa/setuptools#4853]
### setuptools version

setuptools==75.8.1

### Python version

python3.10

### OS

windows

### Description

We have packages using pyproject.toml of the form:

`something.module` that use implicit namespaces for `something`

The latest 75.8.1 seems to rename the `something.module-1.2.3.dist-info` to be instead: `something_module-1.2.3.dist-info`

rolling back to 75.8.0 this problem does not exist.

This breaks folks using something of the form `pkg_resources.require('something.module')` as it now only works if they have `pkg_resources.require('something-module')`

### Expected behavior

packages should continue to have the `something.module` form

### How to Reproduce

```
git clone https://github.com/krpatter-intc/setuptools-example.git
cd setuptools-example
python -m build
```
And you'll note the naming difference in the wheel (and the .dist-info file)

You can then run:

```
import pkg_resources
pkg_resources.require("something.module") # this now throws an exception
```

### Output

```console

```

I'm aware pkg_resources is on its way out, but this still feels bad that the package has a new name. I'm not sure what the new equivalent/replacement for `pkg_resources.require` is.

**Comment by krpatter-intc** [comment]
I realize from the release notes that the wheel renaming was intentional:

https://github.com/pypa/setuptools/issues/4766

But the it's not clear that renaming the .dist-info and the actual package name was indeed intended.

**Comment by keenangraham** [comment]
This issue sounds relevant to what we're experiencing.

We started getting Docker image runtime failures today (very unusual), where as far as we can tell the only difference is `setuptools` version `75.8.0` versus `75.8.1`.

```
...
File "/opt/venv/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 410, in get_context
return loadcontext(object_type, name,
File "/opt/venv/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 299, in loadcontext
return _loaders[scheme](
File "/opt/venv/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
return loader.get_context(object_type, name, global_conf)
File "/opt/venv/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 624, in get_context
entry_point, protocol, ep_name = self.find_egg_entry_point(
File "/opt/venv/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 645, in find_egg_entry_point
pkg_resources.require(self.spec)
File "/opt/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1061, in require
needed = self.resolve(parse_requirements(requirements))
File "/opt/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 888, in resolve
dist = self._resolve_dist(
File "/opt/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 929, in _resolve_dist
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zope.interface==5.3.0' distribution was not found and is required...
```

Also:
`pkg_resources.DistributionNotFound: The 'repoze.debug==1.1' distribution was not found`

So seems related to packages with `.` in name, and https://github.com/pypa/setuptools/issues/3777 actually mentions `zope.interface` so guessing it's related.

Our solution was to bump `PasteDeploy` package, which apparently dropped setuptools dependency and started using importlib.metadata instead: https://docs.pylonsproject.org/projects/pastedeploy/en/latest/news.html

Not sure there is fix needed here, but commenting since this broke us in prod.

**Comment by krpatter-intc** [comment]
Well...the spec itself is not consistent in this regard:

> This is equivalent to regular [name normalization](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization) followed by replacing `-` with `_`. Tools consuming wheels must be prepared to accept `.` (FULL STOP)

It implies `.` should still be supported (even though admittedly the example regular expression provided implies the `.` should be changed.

One other thought...doesn't this now mean these two tools will alias? does something like pypi.org prevent both of these packages from existing?

- `something.module`
- `something_module`

If this is the new standard and it already works with all the rest of the eco-system, then we'll work to code up a new equivalent of the `pkg_resources.require`. There's not a direct replacement, but the tools exist in `importlib` to code it up again.

**Comment by hansingt** [comment]
We have the exact same issue for our tooling.

We do use namespaces extensively in our packages and the're now all broken. 🫤

**Comment by abravalheri** [comment]
I think the best way forward here is to create a patch for `pkg_resources` to restore compatibility.  If anyone in the community is interested in giving it a try, please submit a PR.

**Comment by krpatter-intc** [comment]
> I would also like to emphasize that is important for the community to start moving away from pkg_resources. I understand it is complicated, but it is being many years that it is advertised as deprecated, so it is reasonable to expect that the users have started to work at least a little bit on that.

No disgareements on the need to move away, but it's not scheduled for EOL till python3.13. I thought we had till then to remove it from our infrastructure.  It effectively is 3.12 now (or freeze to old setuptools -- which we'll have to do for a bit)

**Comment by krpatter-intc** [comment]
In case it helps: make sure you are pinning in the `[build-system]` otherwise the build-isolation will just grab the latest, regardless of what is in your current venv.

**Comment by di** [comment]
To be clear, there are two separate issues being discussed here:

1. `pkg_resources.require` doesn't correctly normalize project names with periods;
2. wheel filenames now have underscores in project names instead of periods.

The first one is a bug and I've prepared a PR to fix it: https://github.com/pypa/setuptools/pull/4855.

If you're having the second issue, setuptools is now producing the _correct_ filename going forward and you should update your builds accordingly (or pin back `setuptools<75.8.1` until you can).

**Comment by gilamsalem** [comment]
Hi @di 
Thanks for handling that.
Assuming that my issue is indeed the second one, what can be the reason that pinning the setuptools version doesn't solve our issue?
```
...
Collecting setuptools==75.8.0
...
E   pkg_resources.DistributionNotFound: The 'booking.experiment.tracking' distribution was not found and is required by the application
```

**Comment by di** [comment]
@gilamsalem The `pkg_resources.DistributionNotFound` exception is a result of the first issue with `pkg_resources`, not the second issue. Without seeing more logs or the command you're running, it's hard for me to say what you would need to change here.

**Comment by gilamsalem** [comment]
Thanks @di for the quick replies.

So from our side anything we can do to at least temporary unblock us?

Also the code that throws the exception is:
`version = pkg_resources.get_distribution("booking.experiment.tracking").version`

**Comment by di** [comment]
Seems like your issue is a mix of both. The issue with using `get_distribution` will also be resolved by the fix for the first issue. 

Downgrading the version of setuptools used to build `"booking.experiment.tracking"` and rebuilding would resolve this for now (not this may or may not be the same of the version of setuptools that is providing `pkg_resources.get_distribution` to you)

**Comment by abravalheri** [comment]
The CI is working now to release a new patched version of setuptools that should solve the problem with `pkg_Resources.require(...)`.

For people having problems with the exact name of the distribution file has changed a character to `_`, I recommend trying something more flexible like glob patterns/regexes or wildcards in general. Since Setuptools is required to comply with the PyPA standards, the change in the file name itself is not considered a bug.

**Comment by abravalheri** [comment]
> > I would also like to emphasize that is important for the community to start moving away from pkg_resources. I understand it is complicated, but it is being many years that it is advertised as deprecated, so it is reasonable to expect that the users have started to work at least a little bit on that.
> 
> No disgareements on the need to move away, but it's not scheduled for EOL till python3.13. I thought we had till then to remove it from our infrastructure. It effectively is 3.12 now (or freeze to old setuptools -- which we'll have to do for a bit)

Hi @krpatter-intc could you please point out where you found the information about `pkg_resources` and Python 3.13. I was not aware that setuptools maintainers committed to that timeline.

**Comment by valipod** [comment]
> If you're having the second issue, setuptools is now producing the _correct_ filename going forward and you should update your builds accordingly (or pin back `setuptools<75.8.1` until you can).

So this is a `75.8.1` type of change?

**Comment by gilamsalem** [comment]
My problem is solved now with version 75.8.2. Thanks!

**Comment by Zoltag** [comment]
> If you're having the second issue, setuptools is now producing the _correct_ filename going forward and you should update your builds accordingly (or pin back `setuptools<75.8.1` until you can).

Does this mean that implicit namespaces in Python 3.9 is no longer supported by setuptools, post v75.8.0? Or am I missing something obvious?

<kbd>![Image](https://github.com/user-attachments/assets/cf9c2c74-2522-46f5-b2d9-15e5fa1cfe1e)</kbd>

**Comment by abravalheri** [comment]
It does not mean that.

The (machine-readable standardised) name of the generated wheel/sdist file and associated `.dist-info` directories is something separated from its contents. And you can keep having implicit namespace inside of your whell/sdist files.

**Comment by Zoltag** [comment]
> The (machine-readable standardised) name of the generated wheel/sdist file and associated `.dist-info` directories is something separated from its contents. And you can keep having implicit namespace inside of your whell/sdist files even if the names don't contain dots.

I'm sorry, I'm feeling a bit dense this morning. When I build my namespace package using setuptools >75.8.0, it builds fine, the resulting wheel installs fine, but when I try to import the package in Python 3.9, I get a `ModuleNotFound` error. This appears to be because the dist-info file has replaced `.` with `_`. A simple rename of this file to restore the `.`'s allows Python 3.9 to successfully import the module again (this is what I'm trying to demonstrate in my previous screenshot)

Is this something that is meant to be fixed in Python 3.9, or am I missing something here?

**Comment by abravalheri** [comment]
From the point of view of setuptools we have not identified anything else so far that needs fixing in Python 3.9.

For a simple `import` statement the name of the `dist-info` directory should not change things.

The standard recently implemented in setuptools does require the names of `dist-info` directory to have `.`, replaced by `_`, so that is not considered a bug.

**Comment by abravalheri** [comment]
From the point of view of setuptools we have not identified anything else so far that needs fixing in Python 3.9.

For a simple `import` statement the name of the `dist-info` directory should not change things.

The standard recently implemented in setuptools does require the names of `dist-info` directory to have `.`, replaced by `_`, so that is not considered a bug.

**Comment by Zoltag** [comment]
> For a simple `import` statement the name of the `dist-info` directory should not change things. If an error is happening it might be related to the particular Python code written in the file that is being imported? Any chance it is tightly coupled to the directory name?

This is helpful, thank you !

When I build a simple use-case, it works:
<kbd>![Image](https://github.com/user-attachments/assets/c8969eef-220e-42b2-91da-c3f207c0394f)</kbd>

When I add basic version information, it breaks:
<kbd>![Image](https://github.com/user-attachments/assets/ee6ca9f2-cb5d-408d-a965-2ea6178cb282)</kbd>

**Comment by abravalheri** [comment]
I suspect this problem may have already been fixed in the latest versions of `importlib.metadata`... it might be worth checking that. Otherwise we can report the problem with the distribution name normalisation.

(The trouble with stdlib is that the version of the libraries are fixed on the moment of the release, but you may be lucky with `importlib-metadata` backport on PyPI)

**Comment by Zoltag** [comment]
Thank you - I've tested this and with version 8.6.1 installed, the problem persists (added as a dependency in the package wheel)

**Comment by di** [comment]
I confirmed that this is a bug that exists in `importlib.metadata` provided in Python 3.9 (all the way up to 3.9.16) that is fixed in Python 3.10 (starting at 3.10.0).

Looks like this was fixed in https://pypi.org/project/importlib-metadata/2.1.0/ and https://pypi.org/project/importlib-metadata/3.1.0/. The entry at https://github.com/python/importlib_metadata/blob/main/NEWS.rst#v210 says:

> [#253](https://github.com/python/importlib_metadata/pull/253): When querying for package metadata, the lookup now honors [package normalization rules](https://packaging.python.org/specifications/recording-installed-packages/).

@Zoltag Note that if you're unable to upgrade your Python version and instead installing `importlib_metadata` from PyPI, you need to make the following change to your file:

```diff
- from importlib.metadata import version
+ from importlib_metadata import version
```
