### ISSUE TITLE
Bootstrap script unable to locate releases following 20.10.0 release

### ISSUE THREAD

**Issue by idgserpro** [pypa/setuptools#557]
How to test:

Download

https://bootstrap.pypa.io/bootstrap-buildout.py

At the time of this ticket, `__version__` of this file is [**2015-07-01**](https://github.com/buildout/buildout/blob/9ba1e3170a474e6139c9a7eadd32a498c22cb3bb/bootstrap/bootstrap.py).

Run

`python bootstrap-buildout.py`

You get

```
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
Extracting in /tmp/tmpIKldPD
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 124, in _do_download
  File "<string>", line 64, in _build_egg
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 103, in archive_context
  File "/usr/lib/python2.7/zipfile.py", line 714, in __init__
    self._GetContents()
  File "/usr/lib/python2.7/zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 763, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

You get the same error with 20.10.0.

`python bootstrap-buildout.py --setuptools-version=20.10.0`

```
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.0.zip
Extracting in /tmp/tmp6G6ZVT
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 124, in _do_download
  File "<string>", line 64, in _build_egg
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 103, in archive_context
  File "/usr/lib/python2.7/zipfile.py", line 714, in __init__
    self._GetContents()
  File "/usr/lib/python2.7/zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 763, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

20.9.0 works fine, so this bug was introduced in 20.10.x.

`python bootstrap-buildout.py --setuptools-version=20.9.0`

```
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.9.0.zip
Extracting in /tmp/tmpXrDIjV
Now working in /tmp/tmpXrDIjV/setuptools-20.9.0
Building a Setuptools egg in /tmp/bootstrap-OVHpkN
warning: no files found matching '*' under directory 'setuptools/_vendor'
warning: no files found matching '*.txt'
/tmp/bootstrap-OVHpkN/setuptools-20.9.0-py2.7.egg
```

**Comment by sbocconi** [comment]
The same, breaks Vagrant/Puppet installation:
`wget https://bootstrap.pypa.io/ez_setup.py -O /.puphpet-stuff/ez_setup.py && python /.puphpet-stuff/ez_setup.py`

```
--2016-04-25 15:46:44--  https://bootstrap.pypa.io/ez_setup.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 185.31.17.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|185.31.17.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12059 (12K) [text/x-python]
Saving to: ‘/.puphpet-stuff/ez_setup.py’

100%[====================================================================================================================================================================================================>] 12,059      --.-K/s   in 0s      

2016-04-25 15:46:44 (77.5 MB/s) - ‘/.puphpet-stuff/ez_setup.py’ saved [12059/12059]

Extracting in /tmp/tmp32iyZh
Traceback (most recent call last):
  File "/.puphpet-stuff/ez_setup.py", line 415, in <module>
    sys.exit(main())
  File "/.puphpet-stuff/ez_setup.py", line 412, in main
    return _install(archive, _build_install_args(options))
  File "/.puphpet-stuff/ez_setup.py", line 52, in _install
    with archive_context(archive_filename):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/.puphpet-stuff/ez_setup.py", line 103, in archive_context
    with ContextualZipFile(filename) as archive:
  File "/.puphpet-stuff/ez_setup.py", line 87, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by FrancescoRizzi** [comment]
I just hit the same "File is not a zip file" error by simply downloading ez_setup.py from [the official recommended source](https://bootstrap.pypa.io/ez_setup.py) and running it

**Comment by cyrilgdn** [comment]
Seems that the problem is: https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package and ez_setup has the old pypi URL format hard-coded.... 
(He use https://pypi.python.org/pypi/setuptools/json to get last version but not right URLs :-(  )

**Comment by idgserpro** [comment]
@jaraco Do you have any idea if it's possible to add a test case in setuptools for this situation?

**Comment by idgserpro** [comment]
@cyrilgdn Indeed, the xml invalid response from the url comes as a 313 bytes zip file. Try https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip and you get

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>source/s/setuptools/setuptools-20.10.1.zip</Key>
<RequestId>DAC65125FC40ADDB</RequestId>
<HostId>NqleAbKasjoaBoOZhowtOhluWuTzEgiZZ0HIbREPxqq9wxn6VbbdT0P5r+okwXAk4lzIq597yFA=</HostId>
</Error>
```

https://pypi.python.org/packages/source/s/setuptools/setuptools-20.9.0.zip works.

@dstufft if possible, any news for https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package#comment-27245473?

@jaraco would it be the case to add a `_resolve_setuptools_url_download` like we have `_resolve_version` in ez_setup.py?

**Comment by jimfulton** [comment]
There's a pull request if someone would review it please.

**Comment by foursue** [comment]
+1

**Comment by idgserpro** [comment]
Can we safely use pypi.io in the state it's now, in pre-production? As of now, we have these statistics for setuptools:

```
Downloads (All Versions):
581 downloads in the last day
1173985 downloads in the last week
5004041 downloads in the last month
```

Is pypi.io able to handle the load? I'm not into PYPI 2.0 project so I don't have clues about that.

IMHO, I would like to have the fix done for pypi.io in https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package#comment-27243225 in pypi.python.org as well, but don't know if it's possible. @dstufft is it possible/feasible? Is this workaround *temporary*? If so, for how long?

**Comment by AltxSF** [comment]
Even with the proposed fix it's failing because after curl follows the redirect it gets back this instead of the zip file:

<html>
  <head>
    <title>503 Backend is unhealthy</title>
  </head>
  <body>
    <h1>Error 503 Backend is unhealthy</h1>
    <p>Backend is unhealthy</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sea1920-SEA 1461617605 2489261599</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by jimfulton** [comment]
Folks, my PR fixes this.

It used pypi.io and it adds the --location option to curl.

**Comment by AltxSF** [comment]
Even with --location there is still a problem, after following the redirect curl gets "503 backend is unhealthy"

**Comment by dstufft** [comment]
Can you post the full output of ``curl -I -L https://pypi.io/packages/source/s/setuptools/setuptools-20.10.1.zip``?

**Comment by AltxSF** [comment]
HTTP/1.1 307 Temporary Redirect
Location: https://pypi.io/packages/86/ee/622e83b0dbede6d48891ed209fa5ca83fcc485f9b6696cf56796eda40806/setuptools-20.10.1.zip
Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self'; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.herokuapp.com/ https://secure.gravatar.com; referrer origin-when-cross-origin; reflected-xss block; script-src 'self'; style-src 'self' fonts.googleapis.com
Content-Type: text/html; charset=UTF-8
Fastly-Debug-Digest: f818a9d273c74b910043cc2618e95042641febdc6f083cba11f0c22d331d72b5
Content-Length: 298
Accept-Ranges: bytes
Date: Mon, 25 Apr 2016 23:05:44 GMT
Connection: keep-alive
X-Served-By: cache-iad2141-IAD, cache-sea1920-SEA
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1461625543.980358,VS0,VE123
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none

HTTP/1.1 503 Backend is unhealthy
Retry-After: 0
Content-Type: text/html; charset=utf-8
Content-Length: 454
Accept-Ranges: bytes
Date: Mon, 25 Apr 2016 23:05:44 GMT
Connection: keep-alive
X-Served-By: cache-sea1920-SEA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1461625544.111357,VS0,VE1
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none

**Comment by jaraco** [comment]
I will try to merge the PR and update the bootstrap bookmark.

**Comment by dstufft** [comment]
@AltxSF Sorry, can you do that one more time with a ``-v`` added to it as well?

**Comment by AltxSF** [comment]
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.0.223...
* Connected to pypi.io (151.101.0.223) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: businessCategory=Private Organization; 1.3.6.1.4.1.311.60.2.1.3=US; 1.3.6.1.4.1.311.60.2.1.2=Delaware; serialNumber=3359300; street=16 Allen Rd; postalCode=03894-4801; C=US; ST=NH; L=Wolfeboro,; O=Python Software Foundation; CN=www.python.org
* 	 start date: 2014-09-05 00:00:00 GMT
* 	 expire date: 2016-09-09 12:00:00 GMT
* 	 subjectAltName: pypi.io matched
* 	 issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
* 	 SSL certificate verify ok.
> HEAD /packages/source/s/setuptools/setuptools-20.10.1.zip HTTP/1.1
> User-Agent: curl/7.35.0
> Host: pypi.io
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Location: https://pypi.io/packages/86/ee/622e83b0dbede6d48891ed209fa5ca83fcc485f9b6696cf56796eda40806/setuptools-20.10.1.zip
< Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self'; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.herokuapp.com/ https://secure.gravatar.com; referrer origin-when-cross-origin; reflected-xss block; script-src 'self'; style-src 'self' fonts.googleapis.com
< Content-Type: text/html; charset=UTF-8
< Fastly-Debug-Digest: f818a9d273c74b910043cc2618e95042641febdc6f083cba11f0c22d331d72b5
< Content-Length: 298
< Accept-Ranges: bytes
< Date: Mon, 25 Apr 2016 23:12:29 GMT
< Connection: keep-alive
< X-Served-By: cache-iad2149-IAD, cache-sea1921-SEA
< X-Cache: MISS, MISS
< X-Cache-Hits: 0, 0
< X-Timer: S1461625949.136318,VS0,VE98
< Vary: Accept-Encoding
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< 
  0   298    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host pypi.io left intact
* Issue another request to this URL: 'https://pypi.io/packages/86/ee/622e83b0dbede6d48891ed209fa5ca83fcc485f9b6696cf56796eda40806/setuptools-20.10.1.zip'
* Found bundle for host pypi.io: 0xad69c0
* Re-using existing connection! (#0) with host pypi.io
* Connected to pypi.io (151.101.0.223) port 443 (#0)
> HEAD /packages/86/ee/622e83b0dbede6d48891ed209fa5ca83fcc485f9b6696cf56796eda40806/setuptools-20.10.1.zip HTTP/1.1
> User-Agent: curl/7.35.0
> Host: pypi.io
> Accept: */*
> 
< HTTP/1.1 503 Backend is unhealthy
< Retry-After: 0
< Content-Type: text/html; charset=utf-8
< Content-Length: 454
< Accept-Ranges: bytes
< Date: Mon, 25 Apr 2016 23:12:29 GMT
< Connection: keep-alive
< X-Served-By: cache-sea1921-SEA
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1461625949.243171,VS0,VE0
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< 
  0   454    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host pypi.io left intact
HTTP/1.1 307 Temporary Redirect
Location: https://pypi.io/packages/86/ee/622e83b0dbede6d48891ed209fa5ca83fcc485f9b6696cf56796eda40806/setuptools-20.10.1.zip
Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self'; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.herokuapp.com/ https://secure.gravatar.com; referrer origin-when-cross-origin; reflected-xss block; script-src 'self'; style-src 'self' fonts.googleapis.com
Content-Type: text/html; charset=UTF-8
Fastly-Debug-Digest: f818a9d273c74b910043cc2618e95042641febdc6f083cba11f0c22d331d72b5
Content-Length: 298
Accept-Ranges: bytes
Date: Mon, 25 Apr 2016 23:12:29 GMT
Connection: keep-alive
X-Served-By: cache-iad2149-IAD, cache-sea1921-SEA
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1461625949.136318,VS0,VE98
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none

HTTP/1.1 503 Backend is unhealthy
Retry-After: 0
Content-Type: text/html; charset=utf-8
Content-Length: 454
Accept-Ranges: bytes
Date: Mon, 25 Apr 2016 23:12:29 GMT
Connection: keep-alive
X-Served-By: cache-sea1921-SEA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1461625949.243171,VS0,VE0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none

**Comment by dstufft** [comment]
@AltxSF Try it now and see if it works.

**Comment by AltxSF** [comment]
yes, it works now.

**Comment by dstufft** [comment]
Ok good, misconfiguration in the CDN. Sorry about that!

**Comment by ewang320** [comment]
@dstufft I might be missing something. What exactly do I need to bypass the error. I ran 
curl https://bootstrap.pypa.io/ez_setup.py -o - | python and same error persists

**Comment by ernix** [comment]
@ewang320, try `curl https://bootstrap.pypa.io/ez_setup.py -o - | sed -s "/^DEFAULT_VERSION/ { s/LATEST/'20.9.0'/ }" | python` as a temporary fix

**Comment by ernix** [comment]
@ewang320 try `curl https://bootstrap.pypa.io/ez_setup.py -o - | python - --version=20.9.0`

**Comment by jaraco** [comment]
I've merged the pull requests for the bootstrap script. Please report back if that doesn't correct the issue.

**Comment by FrancescoRizzi** [comment]
Sorry, I'm still getting the same error.
Downloaded [ez_setup from here](https://bootstrap.pypa.io/ez_setup.py), but still get:

```
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by jimfulton** [comment]
Is that the full traceback?

Do you have curl or wget installed?

**Comment by FrancescoRizzi** [comment]
Sorry. Full output is here:

```
%> python ez_setup.py
Extracting in /var/folders/5f/zvqgl88j47zbqzcydcncpzz8nvzfxy/T/tmpQjnOme
Traceback (most recent call last):
  File "ez_setup.py", line 415, in <module>
    sys.exit(main())
  File "ez_setup.py", line 412, in main
    return _install(archive, _build_install_args(options))
  File "ez_setup.py", line 52, in _install
    with archive_context(archive_filename):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "ez_setup.py", line 103, in archive_context
    with ContextualZipFile(filename) as archive:
  File "ez_setup.py", line 87, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```


Also, I have used the suggested curl to get v.20.9 so I'm moving on in the meanwhile, but will try and get 20.10 asap. Thanks

**Comment by jaraco** [comment]
@FrancescoRizzi, I think the issue might be that you have a bad download locally. If ez_setup.py finds a local copy, it doesn't attempt to download it again. If you remove the local (probably small) zip file and re-run the script, I expect it will work. I've tested the latest bootstrap script on OS X and Ubuntu (with and without curl) and the download executes normally as expected.

**Comment by jaraco** [comment]
In #562, I also confirmed the fix works for Windows.

**Comment by idgserpro** [comment]
@jaraco When we use bootstrap-buildout.py, and there's a bad download locally, it doesn't matter because setuptools is always downloaded: if you want to use a local copy, you need to explicitly call

`python bootstrap-buildout.py --setuptools-to-dir=.`

Shouldn't we have the same behavior in ez_setup.py? Always download but give the option to use a local copy, if needed? We're asking this because this "bad download" error is really confusing for beginners, since [this is the official primary method of installation](https://pypi.python.org/pypi/setuptools#unix-wget).

Anyways, thanks for the fast fix.

**Comment by jaraco** [comment]
> Shouldn't we have the same behavior in ez_setup.py?

@idgserpro: I agree. Would you ticket it and consider making a PR?

**Comment by FrancescoRizzi** [comment]
@jaraco thanks for the info. Where would ez_setup find a bad local copy "locally"?
I'm on a Mac OS X El Capitan (10.11.4), and ez_setup was running in an empty directory just created as virtualenv (specifically via virtualenvwrapper mkproject).

I tried to create a new virtualenv, and it seems to install setuptools-18.2.dist-info right away (at least lssitepackages shows that).
For added fun, if I'm out of any virtualenv and do a pip list, I find setuptools (20.3.1)

**Comment by idgserpro** [comment]
@FrancescoRizzi Alongside ez_setup.py itself. And in [this line](https://github.com/pypa/setuptools/blob/d954de8b1f543ee8df0560ffc0a9ceec1bf72fae/ez_setup.py#L340), if there's already a local file, it doesn't download it again.

We tested with *vanilla* `python ez_setup.py`, don't know exactly what could be different from a virtualenv like yourself.

@jaraco Done. Check https://github.com/pypa/setuptools/issues/563. We we'll try to do a PR.

**Comment by jimfulton** [comment]
My suspicion is that @FrancescoRizzi 's ez_setup is deciding not to use wget or curl and is falling back to the "insecure" code and that that code isn't handling the redirect properly.

I'm going to play with this later when I have some time. It might though be helpful for @FrancescoRizzi to add a pdb.sey_trace() to ez_setup.py to walk through what it's actually doing.

**Comment by idgserpro** [comment]
@jaraco I didn't follow setuptools bitbucket-github migration, but this issue was created 5 days ago in bitbucket https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package. Are you planning to keep both repositories? Since you migrated the issues to github as well, wouldn't it be the case to at least close bitbucket issues? Just my 0.02c.

**Comment by jaraco** [comment]
@idgserpro: That issue was created against the PyPI project, not Setuptools. A distinction which I missed initially as well. Setuptools issues are marked private, so aren't visible except to developers.

**Comment by FrancescoRizzi** [comment]
Hi.. I gave it another twirl this morning. Sadly I'm still getting the Bad Zip Error.

I tried it in 3 separate virtualenvs:

1) a virtualenv that existed and had setuptools 18.2, but from which I removed everything that seemed related to setuptools and/or easy_install (both from the project and virtualenv/lib/python2.7/site-packages

2) a virtualenv that existed (had setuptools 18.2), where I didn't do the steps I did in 1

3) a new virtualenv, just created

In all 3 cases I grabbed [ez_setup.py this morning](https://bootstrap.pypa.io/ez_setup.py), and ran python with it.

The stack trace from test3 (below) seems to indicate download_setuptools elected to actually download a new copy of setuptools (20.10.1)

Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
Extracting in /var/folders/5f/zvqgl88j47zbqzcydcncpzz8nvzfxy/T/tmpJiCjcG
Traceback (most recent call last):
  File "ez_setup.py", line 415, in <module>
    sys.exit(main())
  File "ez_setup.py", line 412, in main
    return _install(archive, _build_install_args(options))
  File "ez_setup.py", line 52, in _install
    with archive_context(archive_filename):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "ez_setup.py", line 103, in archive_context
    with ContextualZipFile(filename) as archive:
  File "ez_setup.py", line 87, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

In fact, at the end of this run, there is a (newly created/downloaded) setuptools-20.10.1.zip next to ez_setup.py, sized at 313 bytes. I opened it via double-click (on Mac) to peek, and found just a setuptools-20.10.1.zip.cpgz inside.

Am willing to add print statements (or pdb) to ez_setup and rerun, if we're looking for anything in particular.

**Comment by idgserpro** [comment]
@FrancescoRizzi maybe your network is making cache:

https://bootstrap.pypa.io/ez_setup.py

**Comment by FrancescoRizzi** [comment]
@idgserpro you got it!

So... a hard reload/refresh of the ez_setup source got me a new copy (which i recognized as such thanks to the added `Maintained at https://github.com/pypa/setuptools/tree/bootstrap.` comment at the top). Running that ez_setup seems to finally get me an acceptable setuptools-20.10.1

If I may suggest, I'd add a version number at the top of ez_setup (it may not change often, but when it does it may help in recognizing a specific version of the file).

Thanks though! Now off to hunt every copy of the old ez_setup I have locally :D

**Comment by idgserpro** [comment]
> If I may suggest, I'd add a version number at the top of ez_setup (it may not change often, but when it does it may help in recognizing a specific version of the file).

Good idea.

@jaraco buildout does this with [bootstrap.py](https://github.com/buildout/buildout/commit/6d7b39c0fe94dfc0481b0b6ebc0d9b3915af803d).

**Comment by jaraco** [comment]
Why not just use the date of the file, rather than add additional steps to the change process (and potential for mismatch)?

**Comment by idgserpro** [comment]
What you mean by "date of the file"?

**Comment by idgserpro** [comment]
Is ez_setup.py synced every 15 minutes to https://bootstrap.pypa.io/ez_setup.py like @dstufft suggested in https://github.com/buildout/buildout/issues/86#issuecomment-114944317?

**Comment by jaraco** [comment]
> What do you mean by "date of the file"?

$ curl -s -I https://bootstrap.pypa.io/ez_setup.py | grep Last-Modified
Last-Modified: Tue, 26 Apr 2016 16:30:27 GMT

Annoyingly, Github doesn't seem to provide a Last-Modified date, but does provide an ETag header:

$ curl -s -I https://raw.githubusercontent.com/pypa/setuptools/bootstrap/ez_setup.py | grep ETag
ETag: "e05e52bf1d9cdeed93c16f6456e2c532f343fa22"

> Is ez_setup.py synced every 15 minutes to ...

Yes.
